# Generated by Django 5.0.3 on 2024-03-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rental_period', models.IntegerField(blank=True, null=True)),
                ('photo_book', models.ImageField(upload_to='photos')),
                ('photo_author', models.ImageField(upload_to='photos')),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('avaliable', 'avaliable'), ('rented', 'rented'), ('sold', 'sold')], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book', to='book.category')),
            ],
        ),
    ]
