# Generated by Django 5.0 on 2024-04-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_total_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rental_price',
            new_name='rental_price_per_day',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='total_rental',
            new_name='total_rental_price',
        ),
    ]
